runtime: python312

entrypoint: gunicorn server.server.server.wsgi:application --bind 0.0.0.0:8000

env_variables:
  DJANGO_SETTINGS_MODULE: "server.server.server.settings"


handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

