# Generated by Django 5.1.3 on 2024-12-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='previews_id',
            field=models.ManyToManyField(to='destinations.preview'),
        ),
    ]
