# Generated by Django 5.1.3 on 2024-12-12 02:32

import destinations.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_destination_previews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='previews',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=destinations.models.get_default_list_value, size=None),
        ),
    ]
