# Generated by Django 5.1.3 on 2024-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_alter_destination_image_alter_destination_previews'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
